[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zecshield_mvp = "BV7XujGrrEC5VTQrgRNfrta2HWfHs3Hk4vBfe9FWTx4N"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
